server:
  port: 9105
  tomcat:
    max-http-form-post-size: -1
spring:
  application:
    name: manuscript
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  data:
    neo4j:
      username: neo4j
      password: root
      uri: neo4j://109.244.159.194:7687
  profiles:
    active: dev

logging:
  config: classpath:logback.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl